---
- name: Install k8s dependencies
  apt:
    name: 
      - ca-certificates
      - curl
      - apt-transport-https
    state: present
    update_cache: yes

- name: Disable swap
  ansible.builtin.command: swapoff -a
 
- name: Create folder for keyrings
  become: true
  ansible.builtin.shell: mkdir /etc/apt/keyrings | sudo chmod 777 /etc/apt/keyrings

- name: Add gpg key
  apt_key:
    url: "{{ k8s_gpg_key }}"
    state: present
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add repository
  apt_repository: 
    repo: "{{ k8s_apt_repo }}"
    state: present

- name: Install k8s
  apt:
    name:
      - kubectl
      - kubeadm
      - kubelet
    
- name: Restart kubelet
  service:
    name: kubelet
    state: restarted

- name: Enable kubelet
  become: true
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true

- name: Create a configuration file for containerd and set it to default
  ansible.builtin.shell: |
    mkdir -p /etc/containerd
    containerd config default | sudo tee /etc/containerd/config.toml

- name: Set cgroupdriver to systemd
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    line: SystemdCgroup = true
    state: present

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted