---
- name: Copy manifest directory
  copy: src=../manifests dest=/home/ubuntu

- name: Run manifest create nginx ingress controller
  become: false
  shell: kubectl apply -f /home/ubuntu/manifests/ingress-controller.yaml

- name: Clone kube-prometheus 
  ansible.builtin.git:  
    repo: "https://github.com/prometheus-operator/kube-prometheus.git"  
    dest: "/home/ubuntu/kube-prometeus"  
    version: "release-0.14"  
    force: yes
    update: yes 

- name: Replace grafana config
  shell: "{{ item }}"
  with_items:
   - cp /home/ubuntu/manifests/grafana-config.yaml /home/ubuntu/kube-prometeus/manifests/grafana-config.yaml
   - cp /home/ubuntu/manifests/grafana-networkPolicy.yaml /home/ubuntu/kube-prometeus/manifests/grafana-networkPolicy.yaml

- name: Run manifest to create kube-prometheus
  become: false
  shell: "{{ item }}"
  with_items:
   - kubectl apply --server-side -f /home/ubuntu/kube-prometeus/manifests/setup
   - kubectl wait --for condition=Established --all CustomResourceDefinition --namespace=monitoring
   - kubectl apply -f /home/ubuntu/kube-prometeus/manifests
   - kubectl patch deployment -n monitoring grafana --patch-file /home/ubuntu/manifests/grafana-deployment-path.yaml
   - kubectl apply -f /home/ubuntu/manifests/ingress-grafana.yaml