name: Terraform Infrastructure
on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/create_infrastructure/**'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    name: Terraform Plan/Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/create_infrastructure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Create credentials file
        run: |
          cat <<EOF > .aws/credentials
          ${{ secrets.YC_SA_CREDENTIALS }}
          EOF

      - name: Create TF vars file
        run: |
          cat <<EOF > main.auto.tfvars
          ${{ secrets.TF_VARS }}
          EOF

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
            -backend-config="shared_credentials_files=.aws/credentials"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve 
