name: Terraform Infrastructure
on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/create_infrastructure/**'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    name: Terraform Plan/Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/create_infrastructure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Configure AWS Credentials  
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }} 
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}

      - name: Create TF vars file
        run: |
          cat <<EOF > main.auto.tfvars
          ${{ secrets.TF_VARS }}
          EOF

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve 
